Project_Test2/Project_Test2/Controllers/DETAILsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_Test2.Models;

namespace Project_Test2.Controllers
{
    public class DETAILsController : Controller
    {
        private Project_Test2Context db = new Project_Test2Context();

        //GET: DETAILs
        public ActionResult Index(int? id)
        {
            ViewBag.Model = db.DETAILs.Where(x => x.MAHD == id);

            ViewBag.MASP = new SelectList(db.SANPHAMs, "MASP", "TENSP");
            ViewBag.MAHD = id;
            return View();
        }
        public ActionResult IndexADD(int? id, int flag)
        {
            ViewBag.Model = db.DETAILs.Where(x => x.MAHD == id);

            ViewBag.MASP = db.SANPHAMs;
            ViewBag.MAHD = id;
            ViewBag.Flag = flag;


            return View();
        }

        // GET: DETAILs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETAIL dETAIL = db.DETAILs.Find(id);
            if (dETAIL == null)
            {
                return HttpNotFound();
            }
            return View(dETAIL);
        }

        // GET: DETAILs/Create
        //public ActionResult Create(int? id)
        //{



        //    return View(db.DETAILs.ToList());
        //}

        // POST: DETAILs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MADT,MAHD,SOLUONG,MASP,TENSP,GIANHAP,GIABAN,TIEN,NGAYBAN")] DETAIL dETAIL)
        {

            SANPHAM sp = db.SANPHAMs.Find(dETAIL.MASP);
            dETAIL.GIANHAP = sp.GIANHAP;
            dETAIL.GIABAN = sp.GIANHAP * sp.LOINHUAN / 100;
            dETAIL.TIEN = dETAIL.GIABAN * dETAIL.SOLUONG;
            dETAIL.TENSP = sp.TENSP;


            db.DETAILs.Add(dETAIL);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = dETAIL.MAHD });



        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CREATEADD([Bind(Include = "MADT,MAHD,SOLUONG,MASP,TENSP,MALO,GIANHAP,GIABAN,TIEN,NGAYBAN")] DETAIL dETAIL)
        {
            dETAIL.MALO = dETAIL.MASP.Substring(6);
            dETAIL.MASP = dETAIL.MASP.Substring(0, 6);
            var listsp = db.SANPHAMs.Where(x => (x.MASP == dETAIL.MASP) && (x.MALO == dETAIL.MALO));
            SANPHAM sp = listsp.FirstOrDefault();

            if (sp.SL < dETAIL.SOLUONG)
            {
                int flag = 0;

                return RedirectToAction("IndexADD", new { id = dETAIL.MAHD, flag });
            }
            else
            {
                HOADON hOADON = db.HOADONs.Find(dETAIL.MAHD);
                dETAIL.NGAYBAN = hOADON.NGAYBAN;
                dETAIL.GIANHAP = sp.GIANHAP;
                dETAIL.GIABAN = (((sp.GIANHAP * (sp.LOINHUAN+100))/100)*((100-sp.Sale)))/100;
                dETAIL.TIEN = dETAIL.GIABAN * dETAIL.SOLUONG;
                dETAIL.TENSP = sp.TENSP;
                sp.SL = sp.SL - dETAIL.SOLUONG;


                db.DETAILs.Add(dETAIL);
                db.SaveChanges();
                int flag = 1;
                return RedirectToAction("IndexADD", new { id = dETAIL.MAHD, flag });
            }





        }

        // GET: DETAILs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETAIL dETAIL = db.DETAILs.Find(id);
            if (dETAIL == null)
            {
                return HttpNotFound();
            }
            return View(dETAIL);
        }

        // POST: DETAILs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MADT,MAHD,SOLUONG,MASP,TENSP,DONGIA,TIEN,NGAYBAN")] DETAIL dETAIL)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dETAIL).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = dETAIL.MAHD });
            }
            return View(dETAIL);
        }

        // GET: DETAILs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETAIL dETAIL = db.DETAILs.Find(id);
            if (dETAIL == null)
            {
                return HttpNotFound();
            }
            return View(dETAIL);
        }

        // POST: DETAILs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DETAIL dETAIL = db.DETAILs.Find(id);
            db.DETAILs.Remove(dETAIL);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = dETAIL.MAHD });
        }
        public ActionResult Search()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search1([Bind(Include = "start,end")] Search search)
        {

            var data = db.DETAILs.Where(x => (x.NGAYBAN >= search.start) && (x.NGAYBAN <= search.end));
            var data1 = data.GroupBy(x => x.TENSP)
                .Select(g => new TK
                {
                    TENSANPHAM = g.Key,
                    SL = g.Sum(y => y.SOLUONG)
                }
                );


            ViewBag.Model = data1;
            ViewBag.Start = search.start;
            ViewBag.End = search.end;
            return View();


        }
        public ActionResult SearchItem()

        {
            var data = db.SANPHAMs;
            ViewBag.MASP = data.Select(g => g.TENSP).Distinct();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchItem_(DateTime start , DateTime end, string TENSP)
        {

            var data = db.DETAILs.Where(x => (x.NGAYBAN >=start) && (x.NGAYBAN <=end) && (x.TENSP==TENSP));
          

            ViewBag.Model = data;
            ViewBag.Start =start;
            ViewBag.End =end;
            ViewBag.Pro = TENSP;
            return View();


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_Test2/Project_Test2/Controllers/HOADONsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_Test2.Common;
using Project_Test2.Models;

namespace Project_Test2.Controllers
{
    public class HOADONsController : Controller
    {
        public Project_Test2Context db = new Project_Test2Context();

        // GET: HOADONs
        public ActionResult Index()
        {
            var hOADONs = db.HOADONs.Include(h => h.KHACHHANG).Include(h => h.NV);
            var user = (UserLogin)Session[CommonConstants.USER_SEESION];
            ViewBag.UserName = user.Name;
            return View(hOADONs.ToList());
        }

        // GET: HOADONs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOADON hOADON = db.HOADONs.Find(id);
            if (hOADON == null)
            {
                return HttpNotFound();
            }
            return View(hOADON);
        }

        // GET: HOADONs/Create
        public ActionResult Create()
        {
            ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH");
            ViewBag.MANV = new SelectList(db.NVs, "MANV", "HOTEN");
         var user = (UserLogin)Session[CommonConstants.USER_SEESION];
            ViewBag.UserName = user.Name;
            return View();
        }

        // POST: HOADONs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "MAHD,MANV,MAKH,NGAYBAN")] HOADON hOADON)
        //{
        //    var user = (UserLogin)Session[CommonConstants.USER_SEESION];

        //    hOADON.MANV = user.UserID;
        //    if (ModelState.IsValid)
        //    {
        //        db.HOADONs.Add(hOADON);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH", hOADON.MAKH);
        //    ViewBag.MANV = new SelectList(db.NVs, "MANV", "HOTEN", hOADON.MANV);
        //    return View(hOADON);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ADD([Bind(Include = "MAHD,MANV,MAKH,NGAYBAN")] HOADON hOADON)
        {
            var user = (UserLogin)Session[CommonConstants.USER_SEESION];
            hOADON.MANV = user.UserID;

            if (ModelState.IsValid)
            {
                db.HOADONs.Add(hOADON);
                db.SaveChanges();
                ViewBag.MAHD = hOADON.MAHD;
                ViewBag.NGAYBAN = hOADON.NGAYBAN;
                ViewBag.MASP = db.SANPHAMs;
                ViewBag.Model = db.DETAILs.Where(x => x.MAHD == hOADON.MAHD);

                return View();
            }

            ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH", hOADON.MAKH);
            ViewBag.MANV = new SelectList(db.NVs, "MANV", "HOTEN", hOADON.MANV);
            return View(hOADON);
        }
        // GET: HOADONs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOADON hOADON = db.HOADONs.Find(id);
            if (hOADON == null)
            {
                return HttpNotFound();
            }
            ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH", hOADON.MAKH);
            ViewBag.MANV = new SelectList(db.NVs, "MANV", "HOTEN", hOADON.MANV);
            return View(hOADON);
        }

        // POST: HOADONs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MAHD,MANV,MAKH,NGAYBAN")] HOADON hOADON)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hOADON).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MAKH = new SelectList(db.KHACHHANGs, "MAKH", "TENKH", hOADON.MAKH);
            ViewBag.MANV = new SelectList(db.NVs, "MANV", "HOTEN", hOADON.MANV);
            return View(hOADON);
        }

        // GET: HOADONs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOADON hOADON = db.HOADONs.Find(id);
            if (hOADON == null)
            {
                return HttpNotFound();
            }
            return View(hOADON);
        }

        // POST: HOADONs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HOADON hOADON = db.HOADONs.Find(id);
            db.HOADONs.Remove(hOADON);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_Test2/Project_Test2/Controllers/NVsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_Test2.Common;
using Project_Test2.Models;

namespace Project_Test2.Controllers
{
    public class NVsController : Controller
    {
        private Project_Test2Context db = new Project_Test2Context();

        // GET: NVs
        public ActionResult Index()
        {
            var user = (UserLogin)Session[CommonConstants.USER_SEESION];
            ViewBag.UserName = user.Name;
            return View(db.NVs.ToList());
        }

        // GET: NVs/Details/5
        public ActionResult Details()
        {
          
             var user = (UserLogin)Session[CommonConstants.USER_SEESION];
             NV nV = db.NVs.Find(user.UserID);
            if (nV == null)
            {
                return HttpNotFound();
            }
            return View(nV);
        }

        // GET: NVs/Create
        public ActionResult Create()
        {
            var user = (UserLogin)Session[CommonConstants.USER_SEESION];
            if (user.TypeNV == "admin")
            {
                
                ViewBag.UserName = user.Name;
                return View();
            }
            return RedirectToAction("Index");

        }

        // POST: NVs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MANV,HOTEN,GIOITINH,SDT,NGAYSINH,DIACHI,USERNAME,PASSWORD,TYPENV")] NV nV)
        {
            
             
                db.NVs.Add(nV);
                db.SaveChanges();
                return RedirectToAction("Index");
                 

               
           
        }

        // GET: NVs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NV nV = db.NVs.Find(id);
            if (nV == null)
            {
                return HttpNotFound();
            }
            return View(nV);
        }

        // POST: NVs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MANV,HOTEN,GIOITINH,SDT,NGAYSINH,DIACHI,USERNAME,PASSWORD,TYPENV")] NV nV)
        {
            var user = (UserLogin)Session[CommonConstants.USER_SEESION];
            nV.USERNAME = user.UserName;
            nV.TYPENV = user.TypeNV;
            
               
                db.Entry(nV).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
           
           
        }

        // GET: NVs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NV nV = db.NVs.Find(id);
            if (nV == null)
            {
                return HttpNotFound();
            }
            return View(nV);
        }

        // POST: NVs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NV nV = db.NVs.Find(id);
            db.NVs.Remove(nV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult IsAlreadyUsername(string Username)
        {

            return Json(IsUserAvailable(Username));

        }
        public bool IsUserAvailable(string Username)
        {

            var result = db.NVs.Count(x => x.USERNAME == Username);

            bool status;
            if (result > 0)
            {
                //Already registered  
                status = false;
            }
            else
            {
                //Available to use  
                status = true;
            }

            return status;
        }
       

    protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_Test2/Project_Test2/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    @RenderBody()
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/assets/admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/assets/admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/assets/admin/js/sb-admin-2.min.js"></script>

</body>

</html>

Project_Test2/Project_Test2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Contents/CSS/css")

    <link href="/CSS/header.css" rel="stylesheet" />
    <link href="/CSS/menu.css" rel="stylesheet" />
    <link href="/CSS/main.css" rel="stylesheet" />
    <link href="/CSS/table.css" rel="stylesheet" />
    <link href="/CSS/dialog.css" rel="stylesheet" />
    <link href="/CSS/Home.css" rel="stylesheet" />


</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="header">
            <div class="header-left-left">
                <div class="left-content">
                    <div class="left-content-img"></div>
                    <div style="font-size:25px;color:#ffffff;position:relative;top:3px;margin-left:10px;">CUKCUK</div>
                </div>
            </div>
            <div class="header-left">
                <select>
                    <option>Đại dương xanh</option>
                </select>
            </div>
            <div class="header-right">
                <div class="user-center">
                    <div class="header-contact"></div>
                    <div class="header-user">
                        
                        <div class="user-content">

                            <div class="user-name">@ViewBag.UserName</div>
                           
                            @using (Html.BeginForm("Logout", "Login", new { @class = "user-name" }))
                            {
                                @Html.AntiForgeryToken()
                                <input type="submit" value="Đăng xuất"  class="logout"/>
                            }

                            </div>
                    </div>

                </div>

                <div style="height:100%;width:230px;position:absolute;right:270px;">

                    <div class="notify-image"></div>

                    <div">
                        <select>
                            <option>Tiếng Việt(Tiếng Việt)</option>
                        </select>
                </div>


            </div>
            <div class="menu">

                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "link-text" })
                <a class="menu-icon">
                    <span class="icon icon-report"></span>
                    @Html.ActionLink("Thông tin cá nhân", "Details", "NVs", null, new { @class = "link-text" })
                </a>
                <a class="menu-icon">
                    <span class="icon icon-partner"></span>
                    @Html.ActionLink("Nhân viên", "Index", "NVs", null, new { @class = "link-text" })
                </a>
                <a class="menu-icon">
                    <span class="icon icon-purchar"></span>
                    @Html.ActionLink("Khách hàng", "Index", "KHACHHANGs", null, new { @class = "link-text" })
                </a>

                <a class="menu-icon stock">
                    <span class="icon icon-stock"></span>
                    @Html.ActionLink("Quản lý kho", "Index", "SANPHAMs", null, new { @class = "link-text" })

                </a>
                <a class="menu-icon cash">
                    <span class="icon icon-cash"></span>

                    @Html.ActionLink("Quản lý hóa đơn", "Index", "HOADONs", null, new { @class = "link-text" })
                </a>
                <a class="menu-icon charge">
                    <span class="icon icon-charge"></span>
                    @Html.ActionLink("Tạo mới hóa đơn", "Create", "HOADONs", null, new { @class = "link-text" })
                </a>
                <a class="menu-icon promotion-group">
                    <span class="icon icon-promotion-group"></span>
                    @Html.ActionLink("Thống kê cửa hàng", "Search", "DETAILs", null, new { @class = "link-text" })

                </a>
                <a class="menu-icon">
                    <span class="icon icon-report"></span>
                    @Html.ActionLink("Thống kê theo sản phẩm", "SearchItem", "DETAILs", null, new { @class = "link-text" })
                </a>
                <a class="menu-icon">
                <span class="icon icon-report"></span>
                </a>







            </div>
            <div class="maintain-content">

                @RenderBody()


            </div>

            <div class="bottom-table">
                <div class="content-bottom">
                    <div style="text-align:center">&copy; @DateTime.Now.Day/@DateTime.Now.Month/@DateTime.Now.Year - Copyright by DVL</div>
                    <div style="text-align:center">
                        <b>Hotline:</b>0393339026 <b style="margin-left:8px"> Email:</b>loi.dv173241@sis.hust.edu.vn
                    </div>

                </div>
            </div>



            <script src="/Scripts/jquery-3.4.1.min.js"></script>
            <script src="~/Scripts/bootstrap.min.js"></script>
            <script src="~/Scripts/style.js"></script>
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")

            @RenderSection("scripts", required: false)


</body>
</html>