Project_Test2/Project_Test2/Models/DETAIL.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project_Test2.Models
{
    public class DETAIL
    {
        [Key]
        [Required]
        public int MADT { get; set; }

        [Required]
        public int MAHD { get; set; }
        [Required]
        public int SOLUONG { get; set; }
        [Required]
        public string MASP { get; set; }
        [Required]
        public string TENSP { get; set; }
        [Required]
        public string MALO { get; set; }
        [Required]
        public int? GIANHAP { get; set; }
        [Required]
        public int? GIABAN { get; set; }
        [Required]
        public int? TIEN { get; set; }
        [Required]
        public DateTime NGAYBAN { get; set; }
    }
}

Project_Test2/Project_Test2/Models/SANPHAM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Project_Test2.Models
{
    public class SANPHAM
    {
        [Key, Column(Order = 1)]
        [Required]
        public string MASP { get; set; }
        [Required]
        public string TENSP { get; set; }
        [Key, Column(Order = 2)]
        [Required]
        public string MALO { get; set; }
        [Required]
        public int GIANHAP { get; set; }
        [Required]
        public int LOINHUAN { get; set; }
        [Required]
        public int BAOHANH { get; set; }
        [Required]
        public int SL { get; set; }
        public int Sale { get; set; }
        public virtual ICollection<DETAIL> DETAILS { get; set; }
    }
}

Project_Test2/Project_Test2/Controllers/DETAILsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_Test2.Models;

namespace Project_Test2.Controllers
{
    public class DETAILsController : Controller
    {
        private Project_Test2Context db = new Project_Test2Context();

        //GET: DETAILs
        public ActionResult Index(int? id)
        {
            ViewBag.Model = db.DETAILs.Where(x => x.MAHD == id);

            ViewBag.MASP = new SelectList(db.SANPHAMs, "MASP", "TENSP");
            ViewBag.MAHD = id;
            return View();
        }
        public ActionResult IndexADD(int? id, int flag)
        {
            ViewBag.Model = db.DETAILs.Where(x => x.MAHD == id);

            ViewBag.MASP = db.SANPHAMs;
            ViewBag.MAHD = id;
            ViewBag.Flag = flag;


            return View();
        }

        // GET: DETAILs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETAIL dETAIL = db.DETAILs.Find(id);
            if (dETAIL == null)
            {
                return HttpNotFound();
            }
            return View(dETAIL);
        }

        // GET: DETAILs/Create
        //public ActionResult Create(int? id)
        //{



        //    return View(db.DETAILs.ToList());
        //}

        // POST: DETAILs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MADT,MAHD,SOLUONG,MASP,TENSP,GIANHAP,GIABAN,TIEN,NGAYBAN")] DETAIL dETAIL)
        {

            SANPHAM sp = db.SANPHAMs.Find(dETAIL.MASP);
            dETAIL.GIANHAP = sp.GIANHAP;
            dETAIL.GIABAN = sp.GIANHAP * sp.LOINHUAN / 100;
            dETAIL.TIEN = dETAIL.GIABAN * dETAIL.SOLUONG;
            dETAIL.TENSP = sp.TENSP;


            db.DETAILs.Add(dETAIL);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = dETAIL.MAHD });



        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CREATEADD([Bind(Include = "MADT,MAHD,SOLUONG,MASP,TENSP,MALO,GIANHAP,GIABAN,TIEN,NGAYBAN")] DETAIL dETAIL)
        {
            dETAIL.MALO = dETAIL.MASP.Substring(6);
            dETAIL.MASP = dETAIL.MASP.Substring(0, 6);
            var listsp = db.SANPHAMs.Where(x => (x.MASP == dETAIL.MASP) && (x.MALO == dETAIL.MALO));
            SANPHAM sp = listsp.FirstOrDefault();

            if (sp.SL < dETAIL.SOLUONG)
            {
                int flag = 0;

                return RedirectToAction("IndexADD", new { id = dETAIL.MAHD, flag });
            }
            else
            {
                HOADON hOADON = db.HOADONs.Find(dETAIL.MAHD);
                dETAIL.NGAYBAN = hOADON.NGAYBAN;
                dETAIL.GIANHAP = sp.GIANHAP;
                dETAIL.GIABAN = (((sp.GIANHAP * (sp.LOINHUAN+100))/100)*((100-sp.Sale)))/100;
                dETAIL.TIEN = dETAIL.GIABAN * dETAIL.SOLUONG;
                dETAIL.TENSP = sp.TENSP;
                sp.SL = sp.SL - dETAIL.SOLUONG;


                db.DETAILs.Add(dETAIL);
                db.SaveChanges();
                int flag = 1;
                return RedirectToAction("IndexADD", new { id = dETAIL.MAHD, flag });
            }





        }

        // GET: DETAILs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETAIL dETAIL = db.DETAILs.Find(id);
            if (dETAIL == null)
            {
                return HttpNotFound();
            }
            return View(dETAIL);
        }

        // POST: DETAILs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MADT,MAHD,SOLUONG,MASP,TENSP,DONGIA,TIEN,NGAYBAN")] DETAIL dETAIL)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dETAIL).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = dETAIL.MAHD });
            }
            return View(dETAIL);
        }

        // GET: DETAILs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DETAIL dETAIL = db.DETAILs.Find(id);
            if (dETAIL == null)
            {
                return HttpNotFound();
            }
            return View(dETAIL);
        }

        // POST: DETAILs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DETAIL dETAIL = db.DETAILs.Find(id);
            db.DETAILs.Remove(dETAIL);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = dETAIL.MAHD });
        }
        public ActionResult Search()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search1([Bind(Include = "start,end")] Search search)
        {

            var data = db.DETAILs.Where(x => (x.NGAYBAN >= search.start) && (x.NGAYBAN <= search.end));
            var data1 = data.GroupBy(x => x.TENSP)
                .Select(g => new TK
                {
                    TENSANPHAM = g.Key,
                    SL = g.Sum(y => y.SOLUONG)
                }
                );


            ViewBag.Model = data1;
            ViewBag.Start = search.start;
            ViewBag.End = search.end;
            return View();


        }
        public ActionResult SearchItem()

        {
            var data = db.SANPHAMs;
            ViewBag.MASP = data.Select(g => g.TENSP).Distinct();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SearchItem_(DateTime start , DateTime end, string TENSP)
        {

            var data = db.DETAILs.Where(x => (x.NGAYBAN >=start) && (x.NGAYBAN <=end) && (x.TENSP==TENSP));
          

            ViewBag.Model = data;
            ViewBag.Start =start;
            ViewBag.End =end;
            ViewBag.Pro = TENSP;
            return View();


        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_Test2/Project_Test2/Controllers/SANPHAMsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_Test2.Models;

namespace Project_Test1.Controllers
{
    public class SANPHAMsController : Controller
    {

        private Project_Test2Context db = new Project_Test2Context();
        // GET: SANPHAMs
        public ActionResult Index()
        {
            return View(db.SANPHAMs.ToList());
        }

        // GET: SANPHAMs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.SANPHAMs.Find(id);
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            return View(sANPHAM);
        }

        // GET: SANPHAMs/Create
        public ActionResult Create()
        {
            SANPHAM product = new SANPHAM();
            var lastMaSP = db.SANPHAMs.OrderByDescending(c => c.MASP).FirstOrDefault();
            if (lastMaSP == null)
            {
                product.MASP = "S00001";

            }
            else
            {
                //using string substring method to get the number of the last inserted employee's EmployeeID 
                product.MASP = "S" + (Convert.ToInt32(lastMaSP.MASP.Substring(1, lastMaSP.MASP.Length - 1)) + 1).ToString("D5");
            }
            var listsp = db.SANPHAMs.Where(x => x.MASP == product.MASP);
            var lastLot = listsp.OrderByDescending(x => x.MALO).FirstOrDefault();
            if (lastLot == null)
            {
                product.MALO = "L00001";

            }
            else
            {
                product.MALO = "L" + (Convert.ToInt32(lastLot.MALO.Substring(1, lastLot.MALO.Length - 1)) + 1).ToString("D5");
            }


            return View(product);
        }

        // POST: SANPHAMs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MASP,TENSP,MALO,GIANHAP,LOINHUAN,SL,BAOHANH,Sale")] SANPHAM sANPHAM)
        {
            if (ModelState.IsValid)
            {
                db.SANPHAMs.Add(sANPHAM);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sANPHAM);
        }

        // GET: SANPHAMs/Edit/5
        public ActionResult Edit(string MASP, string MALO)
        {
            if (MASP == null || MALO ==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.SANPHAMs.Where(x => (x.MASP == MASP) && (x.MALO==MALO)).FirstOrDefault();
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            return View(sANPHAM);
        }

        // POST: SANPHAMs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MASP,TENSP,MALO,GIANHAP,LOINHUAN,SL,BAOHANH,Sale")] SANPHAM sANPHAM)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sANPHAM).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sANPHAM);
        }

        // GET: SANPHAMs/Delete/5
        public ActionResult Delete(string MASP, string MALO)
        {
            if (MASP == null || MALO==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM sANPHAM = db.SANPHAMs.Where(x => (x.MASP == MASP) && (x.MALO == MALO)).FirstOrDefault();
            if (sANPHAM == null)
            {
                return HttpNotFound();
            }
            return View(sANPHAM);
        }

        // POST: SANPHAMs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string MASP , string MALO)
        {
            SANPHAM sANPHAM = db.SANPHAMs.Where(x => (x.MASP == MASP) && (x.MALO == MALO)).FirstOrDefault();
            db.SANPHAMs.Remove(sANPHAM);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        // POST : AddLot
        public ActionResult ViewAddLot(string id)
        {
            var product = new SANPHAM();
            product.MASP = id;
            var listsp = db.SANPHAMs.Where(x => x.MASP == id);
            var lastLot = listsp.OrderByDescending(x => x.MALO).FirstOrDefault();
            product.TENSP = lastLot.TENSP;
            ViewBag.ProName = lastLot.TENSP;
            if (lastLot == null)
            {
                product.MALO = "L00001";

            }
            else
            {
                product.MALO = "L" + (Convert.ToInt32(lastLot.MALO.Substring(1, lastLot.MALO.Length - 1)) + 1).ToString("D5");
            }
            return View(product);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProLot([Bind(Include = "MASP,TENSP,MALO,GIABAN,LOINHUAN,SL,BAOHANH")] SANPHAM sANPHAM)
        {
            if (ModelState.IsValid)
            {
                db.SANPHAMs.Add(sANPHAM);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sANPHAM);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_Test2/Project_Test2/Views/SANPHAMs/Create.cshtml
@model Project_Test2.Models.SANPHAM

@{
    ViewBag.Title = "Nhập kho";
}

<h2 style="color:#026BB8">Nhập kho</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Chi tiết</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MASP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.MASP)
            @Html.HiddenFor(model => model.MASP)
            @Html.ValidationMessageFor(model => model.MASP)
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Mã lô", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.MALO)
            @Html.HiddenFor(model => model.MALO)
            @Html.ValidationMessageFor(model => model.MALO)
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Tên sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TENSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENSP, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.Label("Đơn giá", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GIANHAP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GIANHAP, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Lợi nhuận(%)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LOINHUAN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LOINHUAN, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Bảo hành", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BAOHANH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BAOHANH, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Khuyến mãi(%)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sale, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại kho", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_Test2/Project_Test2/Views/SANPHAMs/Delete.cshtml
@model Project_Test2.Models.SANPHAM

@{
    ViewBag.Title = "Xóa";
}

<h2 style="color:#026BB8">Xóa thông tin sản phẩm</h2>
<hr/>

<h3>Bạn muốn xóa sản phẩm này khỏi kho?</h3>
<div>
    <h4>Chi tiết</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên sản phấm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENSP)
        </dd>

        <dt>
            Giá nhập
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GIANHAP)
        </dd>
        <dt>
            Lợi nhuận
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LOINHUAN)
        </dd>

        <dt>
            Bảo hành
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BAOHANH)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Quay lại", "Index")
        </div>
    }
</div>

Project_Test2/Project_Test2/Views/SANPHAMs/Details.cshtml
@model Project_Test2.Models.SANPHAM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SANPHAM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TENSP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TENSP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DONGIA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DONGIA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BAOHANH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BAOHANH)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MASP }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project_Test2/Project_Test2/Views/SANPHAMs/Edit.cshtml
@model Project_Test2.Models.SANPHAM

@{
    ViewBag.Title = "Sửa";
}

<h2 style="color:#026BB8">Sửa thông tin sản phẩm</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Chi tiết</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MASP)

    <div class="form-group">
        @Html.Label("Tên sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TENSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TENSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Giá nhập", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GIANHAP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GIANHAP, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Lợi nhuận(%)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LOINHUAN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LOINHUAN, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Khuyến mãi(%)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sale, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Bảo hành", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BAOHANH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BAOHANH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Lưu" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Project_Test2/Project_Test2/Views/SANPHAMs/ViewAddLot.cshtml
@model Project_Test2.Models.SANPHAM

@{
    ViewBag.Title = "Thêm lô";
}

<h2 style="color:#026BB8">Nhập thêm lô cho Sản phẩm @ViewBag.ProName</h2>


@using (Html.BeginForm("CreateProLot", "SANPHAMs"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Chi tiết</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Mã sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.MASP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.MASP)
            @Html.ValidationMessageFor(model => model.MASP)
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Tên sản phẩm", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.TENSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.TENSP)
            @Html.ValidationMessageFor(model => model.TENSP, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Mã lô", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.MALO, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.MALO)
            @Html.ValidationMessageFor(model => model.MALO, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Đơn giá", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GIANHAP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GIANHAP, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Lợi nhuận(%)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LOINHUAN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LOINHUAN, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Số lượng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SL, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Bảo hành", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BAOHANH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BAOHANH, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Khuyến mãi(%)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BAOHANH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BAOHANH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay lại kho", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}